const SET_STOCKS = 'SET_STOCKS';
const SELECT_STOCK = 'SELECT_STOCK';
const SORT_STOCK_BY_PRICE = 'SORT_STOCK_BY_PRICE';
const SORT_STOCK_BY_BREND = 'SORT_STOCK_BY_BREND';
const SORT_STOCK_BY_DATE = 'SORT_STOCK_BY_DATE';

const SET_KOREA = 'SET_KOREA';
const SELECT_KOREA = 'SELECT_KOREA';
const SORT_KOREA_BY_PRICE = 'SORT_KOREA_BY_PRICE';
const SORT_KOREA_BY_BREND = 'SORT_KOREA_BY_BREND';
const SORT_KOREA_BY_DATE = 'SORT_KOREA_BY_DATE';

const SET_ISLOADED = 'SET_ISLOADED';
const CHANGE_IS_LOADING_TRUE = 'CHANGE_IS_LOADING_TRUE';
const CHANGE_IS_LOADING_FALSE = 'CHANGE_IS_LOADING_FALSE';
const DECREASE_PRICE = 'DECREASE_PRICE';
const INCREASE_PRICE = 'INCREASE_PRICE';
const PRICE_DIFFERENT_INDEX = 'PRICE_DIFFERENT_INDEX';
const ADD_IN_BASKET = 'ADD_IN_BASKET';
const DELETE_BASKET_BY_ID = 'DELETE_BASKET_BY_ID';
